### ISSUE TITLE
Question: wpfc_service_type used twice

### ISSUE THREAD

**Issue by cybrid** [WP-for-Church/Sermon-Manager#171]
Hi,
I'm currently writing my own import script and I mentioned that wpfc_service_type is stored in wp_postmeta and in wp_term_relationships.

I find out that it is neccessary in wp_postmeta. 
Can it be skipped in wp_term_relationships or for which reason is it duplicated ?
Thanks for short answer?

**Comment by nikola3244** [comment]
Hey, sorry for a delay in response.

Values in `wp_postmeta` and `wp_term_relationships` are created in WordPress. You could skip creating them - but who knows what unexpected things might happen.

Why not just go with built-in WordPress functions for creating terms? [`wp_insert_term()`](https://codex.wordpress.org/Function_Reference/wp_insert_term) for example

I will close this "issue", since it's not related to Sermon Manager, but you can still reply here and I'll give my advice
