### ISSUE TITLE
Look through BitBucket Issues

### ISSUE THREAD

**Issue by igor-gp** [WP-for-Church/Sermon-Manager#24]
https://bitbucket.org/wpforchurch/sermon-manager-for-wordpress/issues?status=new&status=open

**Comment by nikola3244** [comment]
Oh no... there are more issues

**Comment by designorant** [comment]
I'm glad I've found this!

I'd love if someone looked at this issue:
https://bitbucket.org/wpforchurch/sermon-manager-for-wordpress/issues/72/itunes-summary-doesnt-escape-html-causing

Not sure whether it's still the case though. I've reported it while running `1.9.6` which we've been stuck on since due to a ton of PHP customisation. Looks like there's been quite a few changes to it lately.

**Comment by nikola3244** [comment]
Hey @designorant 

There have been a lot of bug fixes, expecially in 2.0.x.

Can you check if the issue still exists in the latest version?

**Comment by nikola3244** [comment]
I'll close this one because those issues are related to v1 and we will focus mostly on v3 from now on, but we will still support v2. Let's call it "extended support" where we will mostly fix bugs, with few feature changes
