### ISSUE TITLE
Editing an existing sermon?

### ISSUE THREAD

**Issue by hoschi-it** [WP-for-Church/Sermon-Manager#57]
How can I edit an existing sermon? I forgot to give it a title, so I really need to edit it.

**Comment by hoschi-it** [comment]
Oh, sorry, found it. It was a permission thing. I wasn't allowed to edit existing posts.

**Comment by nikola3244** [comment]
I see that you had another issue, but if someone runs into an issue where title is empty, there are actually 4 ways to edit it:

1. WordPress should show `(no title)` instead of the title when you go to sermons listing. You can click on that and it will take you to the standard edit screen
2. You can click on the checkbox in the first column (on sermons listing screen), and then select `Edit` in `Bulk Actions` dropdown (located at the top and bottom left of the table), and then click on `Apply`
3. Go to your database (usually via PhpMyAdmin), open `<prefix>_posts` table, sort by ID descending, and edit `post_title` column of the first row (if you want to edit the latest sermon) that has `wpfc_sermon` in `post_type` column
4. Go to your database (usually via PhpMyAdmin), open `<prefix>_posts` table, sort by ID descending, note the ID in the first row (if you want to edit the latest sermon) that has `wpfc_sermon` in `post_type` column, and go to this URL: `<website url>/wp-admin/post.php?post=<ID you noted>&action=edit`

**Comment by hoschi-it** [comment]
Thank you for this in-depth guide, @nikola3244 ! Really appreciate that.
